#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

# create empty ntopng.start
safe_touch("root/etc/ntopng/ntopng.start");

#
# Event nethserver-ntopng-update 
#
event_templates("nethserver-ntopng-update", qw(
    /etc/ntopng/ntopng.conf
    /etc/httpd/admin-conf.d/ntopng.conf
));
event_actions("nethserver-ntopng-update", qw(
    initialize-default-databases 00
));
event_services("nethserver-ntopng-update", qw(
    ntopng restart
    redis-ntopng restart
    httpd-admin reload
));


#
# Event nethserver-ntopng-save
#
event_templates("nethserver-ntopng-save", qw(
    /etc/ntopng/ntopng.conf
));
event_actions("nethserver-ntopng-save", qw(
    firewall-adjust 70
));
event_services("nethserver-ntopng-save", qw(
    ntopng restart
));


#
# Event interface-update
#
event_templates("interface-update", qw(
    /etc/ntopng/ntopng.conf
));
event_services("interface-update", qw(
    ntopng restart
));

