#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

# read json from stdin
data=$(cat /dev/stdin)

status=$(echo $data | jq -r '.status')
tcp_port=$(echo $data | jq -r '.TCPPort')
interfaces=$(echo $data | jq -r '.Interfaces')
authentication=$(echo $data | jq -r '.Authentication')

if [ "$status" = "enabled" ]; then
    /sbin/e-smith/config setprop ntopng status "$status" TCPPort "$tcp_port" Interfaces "$interfaces" Authentication "$authentication"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
else
    /sbin/e-smith/config setprop ntopng status "$status"

    if [ $? -gt 0 ]; then
        invalid_error
    fi
fi

/sbin/e-smith/signal-event -j nethserver-ntopng-save
if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
fi

success
